#!/opt/auspex_venv/bin/python3
from typing import Dict

import struct
import numpy as np

#from auspex_game.snes.data import RomHeader
from auspex_emu.data import RomHeader

class SNESRom:
    MEMORY = {
        # Common
        'LowRAM': (0x0000, 0x2000),
        'IO': (0x2000, 0x6000),
        'Expansion': (0x6000, 0x8000),
        # LoRom
        'Lo-Header': 0x7FC0,
        'Lo-SRAM': (0x0000, 0x8000),
        'Lo-ROM': (0x8000, 0x10000),
        # HiRom
        'Hi-Header': 0xFFC0,
        'Hi-SRAM': (0x6000, 0x8000),
        'Hi-ROM': (0x0000, 0x10000),
        'Hi-ROM-Mirror': (0x8000, 0x10000),
        # ExHiRom
        'ExHi-SRAM': (0x6000, 0x8000),
        'ExHi-ROM': (0x0000, 0x10000),
        'ExHi-ROM-Mirror': (0x8000, 0x10000),
    }

    BANK = {
        # Common
        'LowRAM': (0x7E, 0x7F),
        'LowRAM-Mirror1': (0x00, 0x40), # 64 mirrors, 1 per bank
        'LowRAM-Mirror2': (0x80, 0xC0), # 64 mirrors, 1 per bank
        'IO' : (0x00, 0x40),
        'IO-Mirror' : (0x80, 0xC0),
        'RAM': (0x7E, 0x80),
        # LoRom
        'Lo-SRAM': (0x70, 0x7E),
        'Lo-SRAM-Mirror': (0xF0, 0x100),
        'Lo-ROM': (0x80, 0x100),
        'Lo-ROM-Mirror': (0x00, 0x7E),
        # HiRom
        'Hi-SRAM': (0x20, 0x40),
        'Hi-SRAM-Mirror': (0xA0, 0xC0),
        'Hi-ROM': (0xC0, 0x100),
        'Hi-ROM-Mirror1': (0x00, 0x40),
        'Hi-ROM-Mirror2': (0x80, 0xC0),
        # ExHiRom
        'ExHi-SRAM': (0x80, 0xC0),
        'ExHi-ROM': (0xC0, 0x100),
        'ExHi-ROM-Ext': (0x40, 0x7E),
    }

    @staticmethod
    def AllocateRom(rom_title: str, mem_mode: int, raw_data: bytes, rom_size: int, ram_size: int) -> int:
        bank_size = None
        if mem_mode == RomHeader.LoRom:
            bank_size, buffer = SNESRom.AllocateLoRom(rom_title, raw_data, rom_size, ram_size)
        elif mem_mode in [RomHeader.HiRom, RomHeader.ExHiRom]:
            bank_size, buffer = SNESRom.AllocateHiRom(rom_title, raw_data, rom_size, ram_size)
        else:
            raise ValueError(f"Unsupported memory mode: [{mem_mode}]")
        return bank_size, buffer

    @staticmethod
    def Validate(header_start_label: str, rom_title: str, rom_data: np.ndarray) -> None:
        """
        Validate the allocated ROM data by extracting the rom_title from the buffer.
        """

        # should be able to pick out the title from the rom_data
        # FIXME: not just Hi-Header!
        hoff = SNESRom.MEMORY[header_start_label]
        check_title = struct.unpack_from('21s', bytes(rom_data[0x00, :].flatten().tolist()), hoff)
        check_title = check_title[0].decode('ascii').strip()
        assert(check_title == rom_title)
        print(f"Allocated [{check_title}]")

    @staticmethod
    def AllocateLoRom(rom_title: str, raw_data: bytes, rom_size: int, ram_size: int):
        """
        The LoROM mapping mode uses 32 KiB banks.
        The first 15 address pins are connected normally,
        but the 16th address pin on the SNES cartridge port
        is not connected to anything.

        The benefit of LoROM is that it is simpler to understand,
        and is closer to what NES developers are used to. LoROM can go up to 4 MiB,
        but past the 2 MiB mark the RAM and I/O are no longer mirrored into the banks.
        For a LoROM game over 2 MiB, it's recommended to put code toward the beginning
        of the ROM, and data toward the end.

        The ROM header resides at the end of the first 32 KiB bank at $007FC0 in the ROM,
        mapped to $00FFC0 in memory.
        """
        bank_size = 1 << 15
        raw_buffer = list(raw_data)
        # max bank range is 0xFF - 0x80 = 0x7F
        # using rom_size / 0xFFFF, we have the
        # bank size
        max_bank_size = (0xFF - 0x80) + 1
        bank_size = min(max_bank_size, ((rom_size * 0x0400) // 0xFFFF))
        max_rom_size = (0x10000 * bank_size)
        # pad up to the nearest bank
        padding = max(0, max_rom_size - len(raw_buffer))
        if padding:
            raw_buffer.extend([0x00] * padding)

        assert(len(raw_buffer) == max_rom_size)
        buffer = np.array(raw_buffer).reshape(bank_size, 0x10000)
        assert(bytes(buffer.flatten().tolist()) == raw_data)
        SNESRom.Validate('Lo-Header', rom_title, buffer)

        return bank_size, buffer.astype(np.bytes_)

    @staticmethod
    def AllocateHiRom(rom_title: str, raw_data: bytes, rom_size: int, ram_size: int):
        """
        The HiROM mapping mode uses 64 KiB banks. It is created by connecting the
        SNES's address pins to the ROM's address pins 1-to-1, without skipping any pins.
        This allows access to a linear view of the entire ROM at $C0-$FF.
        This simplifies programming for data that can cross bank boundaries.
        Additionally it helps fit more data into the ROM, because data that cannot cross
        bank boundaries has fewer bank boundaries to avoid.

        HiROM can be viewed as a superset of LoROM because it still provides access to the
        last 32 KiB of every bank in the LoROM area. Therefore a HiROM game can decide to put
        code in those areas and be programmed as if it were a LoROM game, while still having
        the benefits of 64 KiB data banks.

        The ROM header resides at the end of the first 64 KiB bank at $00FFC0 in the ROM,
        mapped to $00FFC0 in memory.
        """
        bank_size = 1 << 16
        raw_buffer = list(raw_data)
        # max bank range is 0xFF - 0xC0 = 0x4F
        # using rom_size / 0xFFFF, we have the
        # bank size
        max_bank_size = (0xFF - 0xC0) + 1
        bank_size = min(max_bank_size, ((rom_size * 0x0400) // 0xFFFF))
        max_rom_size = (0x10000 * bank_size)
        # pad up to the nearest bank
        padding = max(0, max_rom_size - len(raw_buffer))
        if padding:
            raw_buffer.extend([0x00] * padding)

        assert(len(raw_buffer) == max_rom_size)
        buffer = np.array(raw_buffer).reshape(bank_size, 0x10000)
        assert(bytes(buffer.flatten().tolist()) == raw_data)
        SNESRom.Validate('Hi-Header', rom_title, buffer)

        return bank_size, buffer.astype(np.bytes_)

    def __init__(self, rom_path):
        self._rom_path = rom_path
        self._rom_data = self.load_rom()

        # data
        self._raw_data = None
        self._header_info = None
        self._rom_title = None
        self._mem_mode = None
        self._bank_size = 0
        self._rom_size = 0
        self._ram_size = 0
        self._tiles = []
        self._sprites = []

    def load_rom(self) -> np.ndarray:
        with open(self._rom_path, 'rb') as file:
            self._raw_data = file.read()
        # read ROM header for size info, so that data
        # can be buffered in a more efficient data structure
        self._header_info = self.__read_rom_header__()

        print(f"Parsed header for [{self._rom_path}]:")
        print("--------------------------------------")
        for k,v in self._header_info.items():
            print(f"{k}: {v}")
        print("--------------------------------------")

        # ROM memory mode is known after read_rom_header()
        self._bank_size, rom_data = SNESRom.AllocateRom(
                self._rom_title, self._mem_mode, self._raw_data,
                self._rom_size, self._ram_size)

        print(f"RomBufferShape: {rom_data.shape}")

        return rom_data

    def __read_rom_header__(self) -> Dict[str, str]:
        """Get the ROM header info."""

        if self._raw_data is None:
            print("ROM has not been loaded!")
            return

        header_offset = SNESRom.MEMORY['Lo-Header'] if len(self._raw_data) <= 0x8000 else SNESRom.MEMORY['Hi-Header']
        header_format = '21sBBBBBBBHH'  # Format string for the header

        # calculate checksum
        #   1. Start with a 16-bit checksum = 0.
        #   2. Add every byte from the prepared data to the checksum. (Overflow is discarded.)
        checksum = 0
        for byte in self._raw_data:
            #print(f"{byte}")
            checksum = (checksum + byte) & 0xFFFF
        checksum_complement = checksum ^ 0xFFFF

        header_data = struct.unpack_from(header_format, self._raw_data, header_offset)
        self._rom_title = header_data[0].decode('ascii').strip()
        self._mem_mode = header_data[1] & 0x0F
        rom_speed, map_mode = RomHeader.SpeedAndMode(header_data[1])
        self._rom_size = RomHeader.MemSize(header_data[3])
        self._ram_size = RomHeader.MemSize(header_data[4])

        print(f"??? {[int(b) for b in header_data[0]]}")
        header = {
            'title': self._rom_title,
            'rom_speed': rom_speed,
            'map_mode': map_mode,
            'chipset': RomHeader.Chipset(header_data[2]),
            'rom_size': f"{self._rom_size} KiB",
            'ram_size': f"{self._ram_size} KiB",
            'region': RomHeader.Region(header_data[5]),
            'developer_id': str(header_data[6]),
            'rom_version': str(header_data[7]),
            'checksum_complement': f"{header_data[8]} [{'OK!' if header_data[8] == checksum_complement else 'FAIL!'}]",
            'checksum': f"{header_data[9]} [{'OK!' if header_data[9] == checksum else 'FAIL!'}]",
        }

        return header

    def dump(self):
        """Dump the hex."""

        if self._rom_data is None:
            print("ROM has not been allocated/buffered!")
            return

        for bank in range(self._rom_data.shape[0]):
            print(f'BANK [{hex(bank)}]: {self._rom_data[bank, :]}')

    def extract_tiles(self, tile_start, tile_size, num_tiles):

        if self._rom_data is None:
            print("ROM has not been allocated/buffered!")
            return

        self._tiles = [self._rom_data[tile_start + i * tile_size: tile_start + (i + 1) * tile_size]
                      for i in range(num_tiles)]
        return self._tiles

    def extract_sprites(self, sprite_start, sprite_size, num_sprites):

        if self._rom_data is None:
            print("ROM has not been allocated/buffered!")
            return

        self._sprites = [self._rom_data[sprite_start + i * sprite_size: sprite_start + (i + 1) * sprite_size]
                        for i in range(num_sprites)]
        return self._sprites

    def get_tile_data(self, index):
        if index < len(self._tiles):
            return self._tiles[index]
        else:
            raise IndexError("Tile index out of range")

    def get_sprite_data(self, index):
        if index < len(self._sprites):
            return self._sprites[index]
        else:
            raise IndexError("Sprite index out of range")



if __name__ == "__main__":

    # Example usage
    rom = SNESRom('som.smc')
    # tiles = rom.extract_tiles(tile_start=0x4000, tile_size=32, num_tiles=256)  # Adjust the start and size as needed
    # sprites = rom.extract_sprites(sprite_start=0x8000, sprite_size=64, num_sprites=64)  # Adjust the start and size as needed
    # 
    # # Access a specific tile or sprite
    # tile_data = rom.get_tile_data(0)  # Get the first tile
    # sprite_data = rom.get_sprite_data(0)  # Get the first sprite

    rom.dump()
