#!/opt/venv/bin/python
import rclpy
from rclpy.executors import MultiThreadedExecutor
from video_captioner.video_captioner import VideoCaptioner


def main(args=None):

    rclpy.init(args=args)
    node = VideoCaptioner(
        use_compression=True,
        video_device_idx=0,
        image_rate_hz=60.0,
        caption_rate_sec=1.0
    )
    executor = MultiThreadedExecutor(num_threads=2)
    executor.add_node(node)
    try:
        executor.spin()
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
