<?xml version="1.0"?>
<package format="3">
  <name>snes_overlay_streamer</name>
  <version>0.1.0</version>
  <description>
    SNES-style pyschadelic Pygame overlay, updated via /video_caption topic
  </description>
  <maintainer email="jonbonne@gmail.com">JonBonne</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
